In [11]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [12]:
data_train = []
data_test = []
labels_train = []
labels_test = []
with open("lab4-train.csv") as datafile:
    for line in datafile.readlines():
        row = [int(x) for x in line.split(",")]
        data_train.append(row[:-1])
        labels_train.append(row[4])

with open("lab4-test.csv") as datafile:
    for line in datafile.readlines():
        row = [int(x) for x in line.split(",")]
        data_test.append(row[:-1])
        labels_test.append(row[4])

In [13]:
predictions = []
accuracies = []
matricies = []
names = ["Random Forest","AdaBoost","Gaussian NB","MLP NN","KNN","Logistic Regression","Decision Tree"]
models = []
models.append(RandomForestClassifier(n_jobs=2, random_state=68,n_estimators=30,max_depth=5))
models.append(AdaBoostClassifier(n_estimators=80,learning_rate=0.1,algorithm='SAMME.R'))
models.append(GaussianNB())
models.append(MLPClassifier(solver='lbfgs', alpha=1e-4,hidden_layer_sizes=(6, 9), random_state=1))
models.append(KNeighborsClassifier(n_neighbors=9))
models.append(LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial'))
models.append(DecisionTreeClassifier(max_depth=3))

In [14]:
for i in range(len(models)):
    models[i].fit(data_train, labels_train)
    y_pred = models[i].predict(data_test)
    predictions.append(y_pred)
    acc = accuracy_score(labels_test, y_pred, normalize=1)
    print("\n" + names[i] + ' {0:.2f}%'.format(acc * 100))
    accuracies.append(acc)
    matrix = confusion_matrix(labels_test,y_pred)
    print (matrix)
    matricies.append(matrix)


Random Forest 83.06%
[[228  10]
 [ 41  22]]

AdaBoost 80.40%
[[236   2]
 [ 57   6]]

Gaussian NB 80.07%
[[226  12]
 [ 48  15]]

MLP NN 81.40%
[[231   7]
 [ 49  14]]

KNN 78.41%
[[229   9]
 [ 56   7]]

Logistic Regression 80.73%
[[232   6]
 [ 52  11]]

Decision Tree 81.40%
[[221  17]
 [ 39  24]]


In [48]:
ensemble_y = []
weights_1 = [1,1,1,1,1,1,1]
weights_2 = [1,2,1,2,1,1,3]
for i in range(len(predictions[0])):
    _0 = _1 = 0
    for j in range(2,len(predictions)):
        _0 += weights_2[j] if predictions[j][i] == 0 else 0
        _1 += weights_2[j] if predictions[j][i] == 1 else 0
    ensemble_y.append( 0 if _0 > _1 else 1)
acc = accuracy_score(labels_test, ensemble_y)
matrix = confusion_matrix(labels_test,ensemble_y)
print("Ensemble " + ' {0:.2f}%'.format(acc * 100))
print (matrix)

Ensemble  83.06%
[[229   9]
 [ 42  21]]


In [51]:
ensemble_y = []
weights_1 = [1,1,1,1,1,1,1]
weights_2 = [3,1,1,1,1,1,2]
for i in range(len(predictions[0])):
    _0 = _1 = 0
    for j in range(len(predictions)):
        _0 += weights_2[j] if predictions[j][i] == 0 else 0
        _1 += weights_2[j] if predictions[j][i] == 1 else 0
    ensemble_y.append( 0 if _0 > _1 else 1)
acc = accuracy_score(labels_test, ensemble_y)
matrix = confusion_matrix(labels_test,ensemble_y)
print("Ensemble " + ' {0:.2f}%'.format(acc * 100))
print (matrix)

Ensemble  83.39%
[[228  10]
 [ 40  23]]
